### ISSUE TITLE
Update the GSoC page on the mlpack website

### ISSUE THREAD

**Issue by sreenikSS** [mlpack/mlpack.org#17]
Information on the [GSoC page](https://www.mlpack.org/gsoc.html) is a little outdated. 

> We have been a part of the program in 2013, 2014, 2016, 2017, and 2018, with a total of 30 students accepted for mlpack (all of whom succeeded at the program).

This should be updated to include 2019's contribution too.

**Comment by sreenikSS** [comment]
I have opened a PR for this #18.

**Comment by rcurtin** [comment]
#18 is merged and deployed, so I think we can resolve this now. :)
