### ISSUE TITLE
Databricks How-To

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack.org#27]
This is not really an issue, but a contribution. I struggled to pull the 2GB mlpack.org repo to just add a few lines of text... so here is a gist with a small modification to getstarted.md on how to use mlpack within Databricks. It's not rocket science, but I haven't seen any reference to this and it may be helpful for Databricks-like scientists. I have tested using the latest mlpack version and Databricks Runtime > 5.5.

@rcurtin if you believe it's helpful, could you please include this minor edit?

https://gist.github.com/gmanlan/4b156fd65ce32a7c8007996e5fc78f7d#databricks

**Comment by rcurtin** [comment]
Thanks!  Applied in 4d9b01194.  Sorry about the huge size of the repo---I tried to clean it at one point, but wasn't successful apparently. :(
