### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by bkmgit** [mlpack/mlpack.org#28]
The datasets are obtained by a script from:
https://www.ratml.org/misc/datasets.tar.gz

This makes it hard to add additional datasets. Might it be worth making a separate repository for the datasets?

**Comment by bkmgit** [comment]
GitLab offers 10 GB.
[Zenodo](https://help.zenodo.org/) offers upto 50 Gb.

**Comment by rcurtin** [comment]
Thanks @bkmgit!  I set up the datasets on Zenodo: https://zenodo.org/record/4042173

If there are datasets you want to add, you can download the .tar.gz, add some new datasets, and then we can figure out a way to upload the new .tar.gz.  Or, you can just let me know what files you'd like to add and I can handle it. :+1:

See also: https://github.com/mlpack/mlpack.org/pull/32

**Comment by bkmgit** [comment]
Thanks. The files that would be helpful to have added can be found at:

https://drive.google.com/file/d/1-stKadfTgJLtYsHWqXhGO3nTjKVFxm_Q/view

**Comment by bkmgit** [comment]
One other option might be for any datasets to be uploaded to Zenodo. 
They can have different locations, as long as the download script is 
identified. This would give some flexibility though may require more 
download requests.

**Comment by rcurtin** [comment]
@bkmgit true, maybe we can change it later if needed.  For now just uploading a single .tar.gz seems to work ok.

I added your dataset from #29: https://zenodo.org/record/4064956

Now it's available in mlpack.org/datasets/: http://www.mlpack.org/datasets/dataset_sms_spam_bhs_indonesia_v1.tar.gz

So, I'll go ahead and close this then. :+1:
