### ISSUE TITLE
Benchmarks "Read More" link refers to mlpack.org

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack.org#39]
The "Read More" link at the bottom of the Benchmarks section links to mlpack.org, which is the same page.
![image](https://user-images.githubusercontent.com/40178166/96519117-217d1b80-1221-11eb-9dac-a21e0c3dcafc.png)

**Comment by zoq** [comment]
Thanks for the report, the benchmark page is still work in progress, so let's remove the link for now.

**Comment by zoq** [comment]
Fixed in https://github.com/mlpack/mlpack.org/pull/40.

**Comment by rcurtin** [comment]
#40 is merged and I rebuilt the website, so this seems fixed now. :+1: Thanks for the report @gmanlan!
