### ISSUE TITLE
Incorrect Release Date

### ISSUE THREAD

**Issue by varunagrawal** [mlpack/mlpack.org#4]
The release date for version 3.0.0 is listed as March 30th, 2017, but the blog says 2018.

This is the source of the error: https://github.com/mlpack/mlpack.org/blob/master/index.html#L47

**Comment by rcurtin** [comment]
Oops!  Thank you.  I really appreciate you pointing this out---I'm not sure how long it would have been until anyone noticed otherwise. :)  Fixed in e21aabc1c.

**Comment by varunagrawal** [comment]
No worries. Glad to be of help. :)
Go Jackets!
