### ISSUE TITLE
mailing list links are dead

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack.org#58]
@rcurtin On https://www.mlpack.org/community.html the links to mailing lists appear dead.

The link for "mlpack mailing list" leads to error 404: https://lists.mlpack.org/mailman/listinfo/mlpack

The link for "mlpack-git mailing list" also leads to error 404: https://lists.mlpack.org/mailman/listinfo/mlpack-git

**Comment by rcurtin** [comment]
Thanks for pointing this out!  We upgraded to mailman3, which was its own semi-nightmare, and then I forgot to update the links here.  They're fixed now. :+1:
